fix(revpi-config): update NetworkManager state
NetworkManager uses rfkill to turn WLAN on and off, but it also tracks
the WLAN state separately in
/var/lib/NetworkManager/NetworkManager.state. Since the bookworm image
250801 we deploy a default NetworkManager state file to make sure
NetworkManager doesn't turn WLAN on at first boot, but this also blocks
rfkill from configuring WLAN because the NetworkManager state always
overrides the rfkill state.

When enabling or disabling WLAN with revpi-config by calling it with the
"ieee80211" argument also make sure that NetworkManager is updated. If
it is running it can simply be updated with a nmcli command. If it
isn't, update the state file directly

Note that this *doesn't* check if the WLAN country is set, so WLAN is
still enabled or disabled if no WLAN country is set.

Signed-off-by: Thomas Böhler <t.boehler@kunbus.com>

diff --git a/revpi-config/revpi-config b/revpi-config/revpi-config
--- a/revpi-config/revpi-config
+++ b/revpi-config/revpi-config
@@ -266,6 +266,34 @@ do_service() {
 	return $ret
 }
 
+_set_wlan_state_networkmanager() {
+	local state_file=/var/lib/NetworkManager/NetworkManager.state
+	local action="$1"
+	local enabled=false
+	local radio=off
+
+	case "$action" in
+	enable)
+		enabled=true
+		radio=on
+		;;
+	disable)
+		enabled=false
+		radio=off
+		;;
+	*)
+		printf "BUG: cannot pass '%s' to _set_wlan_state_networkmanager()\n" "$action" >&2
+		return 1
+		;;
+	esac
+
+	if systemctl -q is-active NetworkManager; then
+		nmcli radio wifi "$radio"
+	elif [ -f "$state_file" ]; then
+		sed -i -e "s/^\(WirelessEnabled\)=.*\$/\1=$enabled/" "$state_file"
+	fi
+}
+
 # do_wireless <verb> <type> (where type is "bluetooth" or "ieee80211")
 do_wireless() {
 	shopt -s nullglob
@@ -298,9 +326,11 @@ do_wireless() {
 	case "$1" in
 	enable)
 		[ "$IDX" ] && rfkill unblock "$IDX"
+		_set_wlan_state_networkmanager "$1"
 		;;
 	disable)
 		[ "$IDX" ] && rfkill block "$IDX"
+		_set_wlan_state_networkmanager "$1"
 		;;
 	status)
 		[ -z "$IDX" ] && return 0
