fix(revpi-config): Fix compute module detection
The current approach on checking if the script is running on a CM1 is
erroneous. It assumes that if it is not running on a CM3 or CM4 is will run
on a CM1. This totaly ignores the fact that it could also run on a CM4S.

Fix this by explicitly check for revision code of a CM1 and use inverted value
for is_not_cm1(). Also add guard method for CM4S and re-order the existing
revision guards. Fail if rpi_revision_code() cannot determine the board
revision code and do not try to make any assumptions.

Fixes a1e27f0e789f30487afa940cd9ddf477eae7b531 (and earlier)

Signed-off-by: Nicolai Buchwitz <n.buchwitz@kunbus.com>

diff --git a/revpi-config/revpi-config b/revpi-config/revpi-config
--- a/revpi-config/revpi-config
+++ b/revpi-config/revpi-config
@@ -8,6 +8,9 @@ fi
 CONFIG=/boot/config.txt
 CPUFREQCONFIG=/etc/default/cpufrequtils
 
+trap "exit 1" SIGUSR1
+PROC="$$"
+
 usage() {
 	cat <<-EOF
 	Usage: $(basename $0) enable | disable | status | available <feature>
@@ -45,17 +48,16 @@ do_gui() {
 	esac
 }
 
-is_cm3() {
-	test $(rpi_type) -eq 10
-}
-
-is_not_cm1() {
-	is_cm3 || is_cm4
-}
-
 rpi_revision_code() {
 	# see https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#new-style-revision-codes
 	code=$(grep Revision /proc/cpuinfo | cut -d' ' -f2)
+
+	if [ -z "$code" ]; then
+		echo >&2 "Unable to determine board revision code. Not running on a RevPi?. Aborting."
+		# we are running in a subshell, thus cannot exit directly here
+		kill -10 "$PROC"
+		return
+	fi
 
 	# Convert the hexadecimal revision code to base 10
 	echo $((16#${code}))
@@ -68,8 +70,24 @@ rpi_type() {
 	echo $(((code & mask) >> 4))
 }
 
+is_cm1() {
+	test "$(rpi_type)" -eq 6
+}
+
+is_not_cm1() {
+	! is_cm1
+}
+
+is_cm3() {
+	test "$(rpi_type)" -eq 10
+}
+
+is_cm4s() {
+	test "$(rpi_type)" -eq 21
+}
+
 is_cm4() {
-	test $(rpi_type) -eq 20
+	test "$(rpi_type)" -eq 20
 }
 
 is_cm4_with_wifi() {
