fix(factory-reset): avoid rename(2) for /etc/hosts
Calling "sed" with the "-i" flag results in "sed" writing a temporary
file, then moving it to the original location using the "rename(2)"
syscall.

This can cause problems if the destination file is a bind mount, because
a bind mount file cannot be replaced.

Avoid this problem by modifying the file in memory, then overwriting the
content of the destination file instead. This approach is not atomic,
unlike using the "rename(2)" syscall, but is required to work around it.

This is only implemented for the "/etc/hosts" file because a RevPi Rugix
image persists this through a bind mount.

Signed-off-by: Thomas Böhler <t.boehler@kunbus.com>

diff --git a/revpi-factory-reset/revpi-factory-reset.in b/revpi-factory-reset/revpi-factory-reset.in
--- a/revpi-factory-reset/revpi-factory-reset.in
+++ b/revpi-factory-reset/revpi-factory-reset.in
@@ -188,11 +188,16 @@ else
 fi
 
 hostname="$HOSTNAME_PREFIX$ser"
-if ! sed --follow-symlinks -r -i \
+hosts_path="$(realpath "$ROOT"/etc/hosts)"
+if ! hosts="$(sed -r \
 	-e "s/^(127\.0\.1\.1[[:blank:]]+).*/\1$hostname/" \
-	"$ROOT"/etc/hosts; then
-	die "Unable to write to /etc/hosts. Aborting."
+	"$hosts_path")"; then
+	die "Unable to transform $hosts_path. Aborting."
 fi
+if ! printf '%s' "$hosts" > "$hosts_path"; then
+	die "Unable to write to $hosts_path. Aborting."
+fi
+
 if ! echo "$hostname" > "$ROOT"/etc/hostname; then
 	die "Unable to change hostname. Aborting."
 fi
